### ISSUE TITLE
Great repo!

### ISSUE THREAD

**Issue by rismoney** [jhochwald/Universal-Winlogbeat-configuration#3]
I have found this repo extraordinarily informative and helpful along with the blog https://hochwald.net/ship-windows-event-logs-with-winlogbeat.  

I was wondering, is this is the same configuration you use on domain controllers?
Additionally I was wondering what audit policies you like to turn on in accordance with this.

**Comment by rismoney** [comment]
@jhochwald ?

**Comment by ozinfotech** [comment]
I'm curious as well...

**Comment by jhochwald** [comment]
Yep! You can use the config on all Servers. The ID's relevant for Domain Controllers are captured, at least the ones in which I was interested.
What I did: Instead of logging everything to my SIEM (Graylog) I start logging towards (a dedicated) Logstash Instance. I always start with "Log everything" and start to develop a filter from there on. Events that are not relevant will be filtered on the client... It can take a while to find all the relevant information and filter (reduce) the noise.
It depends on your requirements and the events that you would like to log/see.

Audit: At least the Login part must be turned on (Success and unsuccessful). And like above: It depends on your requirements and your configuration.
My (personal) recommendation: Turn on as much as possible! If you do not need it... Who cares, set up filtering and drop everything that you do not need (on the client or on your target).

Please keep in Mind: This config is now outdated. It is not compatible with newer WinLogBeat versions (The Processors are incompatible). Please see #4 for further information.

There might be an updated version.

**Comment by jhochwald** [comment]
You might find this repo useful: https://github.com/palantir/windows-event-forwarding/tree/master/group-policy-objects
Therefore I have the references within the config
